### ISSUE TITLE
Scipy test failure on AMD cores

### ISSUE THREAD

**Issue by ogrisel** [xianyi/OpenBLAS-CI#10]
Recently the piledriver build failed when running the scipy tests:

```
======================================================================
ERROR: Failure: ValueError (bad marshal data (unknown type code))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
ValueError: bad marshal data (unknown type code)

======================================================================
FAIL: test_iterative.test_convergence(<function cgs at 0x7f4155f1f9b0>, <rand-sym-pd>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/tests/test_iterative.py", line 196, in check_convergence
    assert_equal(info,0)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 355, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 90
 DESIRED: 0
```

The first error is really weird as it does not seem to be related to OpenBLAS at all. I wonder if it's deterministic or not. The second failure (`test_iterative.test_convergence`) also happens in the Barcelona build so I think this is a real issue but more investigation is required to understand what's happening.

**Comment by ogrisel** [comment]
I can reproduce the convergence failure on a docker container hosted on http://getcarina.com (at rackspace) that uses AMD piledriver CPUs.

It is about the [cgs](https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/isolve/iterative.py#L271) solver applied to "rand-sym-pd" data. The cgs solver is in turn using the `scgsrevcom` routine implemented in Fortran:

https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/isolve/iterative/CGSREVCOM.f.src

**Comment by ogrisel** [comment]
The test has failed with `INFO=90` meaning that 90 iterations were performed without convergence.

**Comment by ogrisel** [comment]
Maybe this is related to xianyi/OpenBLAS#834.

**Comment by njsmith** [comment]
Does altering the CORETYPE allow the test to pass?

**Comment by matthew-brett** [comment]
@xianyi - we are holding off distributing our binaries on this issue.   Do you think it will be easy to fix?  Can you suggest a good workaround?

**Comment by xianyi** [comment]
@matthew-brett , @njsmith , I am working on this issue. I think it is easy to find out a workaround.

**Comment by matthew-brett** [comment]
Thank you - that will be very helpful.

**Comment by xianyi** [comment]
@matthew-brett , quick question.

How could I just run `test_iterative.test_convergence`?

I can workaround this bug. However, I met a new one at sklearn.

```
======================================================================
FAIL: sklearn.tests.test_common.test_transformer_n_iter('CCA', CCA(copy=True, max_iter=500, n_components=2, sca\
le=True, tol=1e-06))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/site-packages/sklearn/utils/estimator_checks.py", line 1475, in check_transfor\
mer_n_iter
    assert_greater(iter_, 1)
AssertionError: 1 not greater than 1

----------------------------------------------------------------------
Ran 5343 tests in 172.257s

FAILED (SKIP=18, failures=1)
```

**Comment by matthew-brett** [comment]
You can run the set of iterative solver tests with:

```
nosetests /usr/local/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/tests/test_iterative.py:test_convergence 
```

To find which solver and parameters have failed would be a bit harder because of the way the test is written - let me know if I can help with that?  Or - Olivier - can you track down which it is on your test machine?

Similarly for the scikit-lean test:

```
nosetests /usr/local/lib/python2.7/site-packages/sklearn/tests/test_common.py:test_transformer_n_iter
```

Again, this will run a set of tests ... but a much smaller set than the whole test battery.

**Comment by ogrisel** [comment]
Some more tests on my rackspace machine:

```
root@4591a98ddabc:/# OPENBLAS_CORETYPE=PILEDRIVER nosetests -x /usr/local/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/tests/test_iterative.py:test_convergence
.................F
======================================================================
FAIL: test_iterative.test_convergence(<function cgs at 0x7f869825cc80>, <rand-sym-pd>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/tests/test_iterative.py", line 196, in check_convergence
    assert_equal(info,0)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 375, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: 90
 DESIRED: 0

----------------------------------------------------------------------
Ran 18 tests in 0.239s

FAILED (failures=1)
root@4591a98ddabc:/# OPENBLAS_CORETYPE=BARCELONA nosetests -x /usr/local/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/tests/test_iterative.py:test_convergence
...............................................................................................................................
----------------------------------------------------------------------
Ran 127 tests in 3.396s

OK
root@4591a98ddabc:/# OPENBLAS_CORETYPE=NEHALEM nosetests -x /usr/local/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/tests/test_iterative.py:test_convergence
...............................................................................................................................
----------------------------------------------------------------------
Ran 127 tests in 3.420s

OK
root@4591a98ddabc:/# cat /proc/cpuinfo
processor   : 0
vendor_id   : AuthenticAMD
cpu family  : 21
model       : 2
model name  : AMD Opteron(tm) Processor 4332 HE
stepping    : 0
microcode   : 0x600081f
cpu MHz     : 2999.847
cache size  : 2048 KB
physical id : 0
siblings    : 6
core id     : 0
cpu cores   : 3
apicid      : 16
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb arat cpb hw_pstate npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold vmmcall bmi1
bugs        : fxsave_leak
bogomips    : 5999.69
TLB size    : 1536 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro
```

This is weird: the BARCELONA openblas driver does not crash on this host but it crashes on http://build.openblas.net .

The NEHALEM driver seems to be stable and could be used as a temporary fallback if we want to ship binary wheels for the scipy stack projects with a patched version of OpenBLAS 0.2.17. Of course if @xianyi finds a real fix that even better.

**Comment by ogrisel** [comment]
Actually I made a mistake BARCELONA is fine on build.openblas.net, that's bulldozer that's broken instead. An I get a consistent behavior on my AMD machine:

```
root@4591a98ddabc:/# OPENBLAS_CORETYPE=BULLDOZER nosetests -x /usr/local/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/tests/test_iterative.py:test_convergence
.................F
======================================================================
FAIL: test_iterative.test_convergence(<function cgs at 0x7f84f75b4c80>, <rand-sym-pd>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/tests/test_iterative.py", line 196, in check_convergence
    assert_equal(info,0)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 375, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: 90
 DESIRED: 0

----------------------------------------------------------------------
Ran 18 tests in 0.228s
```

So to recap: BULLDOZER & PILEDRIVER have the bug while but NEHALEM and BARCELONA seem safe to use on this kind of CPU.

**Comment by ogrisel** [comment]
Actually I re-ran the full test suites by forcing both the NEHALEM and BARCELONA drivers and it both cases I got the following failure:

```
======================================================================
FAIL: test_nanmedian_all_axis (test_stats.TestNanFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/scipy/stats/tests/test_stats.py", line 242, in test_nanmedian_all_axis
    assert_equal(len(w), 4)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 375, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: 1
 DESIRED: 4
```

So using those as a fallback is probably not a good idea in the end.

**Comment by ogrisel** [comment]
I did some more tests, and it seems I always get `the test_nanmedian_all_axis` failure on this machine independently of the selected `OPENBLAS_CORETYPE`. I also noticed that I had installed numpy 1.11.0 (instead of numpy==1.10.4 on build.openblas.net). I will re-run the tests with numpy 1.10.4 to check whether this is dependent on the version of numpy.

**Comment by ogrisel** [comment]
Ok I did some googling (I should have started this way) and indeed the random test_nanmedia_all_axis failure should be ignored as unrelated to openblas: https://github.com/scipy/scipy/issues/5656

Sorry for the noise. So to recap: for this AMD piledriver machine, both the BARCELONA and the NEHALEM drivers work while the BULLDOZER and PILEDRIVER drivers are broken.

**Comment by xianyi** [comment]
@ogrisel , I already found the fix for `test_iterative.test_convergence` on AMD piledriver and bulldozer.
I will submit the patch today.

**Comment by ogrisel** [comment]
Great. In case you get the other failure (test_nanmedian_all_axis) let us know and we will make a patch to disable that test.

**Comment by xianyi** [comment]
@ogrisel ，

```
======================================================================
FAIL: sklearn.tests.test_common.test_transformer_n_iter('CCA', CCA(copy=True, max_iter=500, n_components=2, scale=True, tol=1e-06))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/site-packages/sklearn/utils/estimator_checks.py", line 1475, in check_transformer_n_iter
    assert_greater(iter_, 1)
AssertionError: 1 not greater than 1

----------------------------------------------------------------------
```

Do you familiar this failure? Is it related to OpenBLAS?

**Comment by ogrisel** [comment]
I have never seen this one. scikit-learn tests for 0.17.1 are very stable on MKL, ATLAS and Apple Accelerate AFAIK. scikit-learn wasn't extensively tested with openblas previously.

The CCA code in scikit-learn has not a great history of numerical stability so it might be a bug in scikit-learn. Can you only get this failure on AMD CPUs or do your reproduce it on other CPUs with https://github.com/xianyi/OpenBLAS/commit/d4380c1fe4b9c292092145f85bcd70a2728581d2?

**Comment by matthew-brett** [comment]
Olivier - can you reproduce this failure on your Rackspace AMD machine?   We don't get it for the Intel tests on travis-ci or buildbot.

**Comment by ogrisel** [comment]
Yes I can reproduce it on the AMD machine. I will have a deeper look at it.

**Comment by ogrisel** [comment]
By reading the code I think this is a false positive. The test is too strict, it should be `assert_greater_equal(iter_, 1)` or `assert_greater(iter_, 0)`.

Same remark for this other failure:

```
======================================================================
FAIL: sklearn.feature_extraction.tests.test_image.test_reconstruct_patches_perfect_color
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/site-packages/sklearn/feature_extraction/tests/test_image.py", line 195, in test_reconstruct_patches_perfect_color
    np.testing.assert_array_equal(face, face_reconstructed)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 787, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 0.000678168402771%)
 x: array([[[ 146.375   ,  201.1875  ,  228.59375 ],
        [ 123.5     ,  189.75    ,  222.875   ],
        [ 134.      ,  195.      ,  225.5     ],...
 y: array([[[ 146.375   ,  201.1875  ,  228.59375 ],
        [ 123.5     ,  189.75    ,  222.875   ],
        [ 134.      ,  195.      ,  225.5     ],...

----------------------------------------------------------------------
```

It should be `assert_array_almost_equal`. I will open a PR to scikit-learn master.

For OpenBLAS tests I think it's possible to do a `sed`-based patch in the installed `sklearn` package in the `site-packages` folder.

**Comment by xianyi** [comment]
@ogrisel , thank you for the investigation.

**Comment by ogrisel** [comment]
I opened https://github.com/scikit-learn/scikit-learn/pull/6634 to fix the PBM upstream in master but feel free to do the sed based patching in the mean time in OpenBLAS-CI. I have to go offline now. I can help tomorrow if needed.

**Comment by ogrisel** [comment]
I made a real patch for scikit-learn 0.17.1 instead of using sed: see #14.

I tested on an AMD hosted docker container at http://getcarina.com and it seems to work as expected.

**Comment by xianyi** [comment]
@ogrisel ， thank you for the patch.

**Comment by ogrisel** [comment]
Let's close this issue as the test failure reported in the description has been fixed. There are still failures with SVD running on complex data on the streamroller microarchitecture but it's better tracked in issue https://github.com/xianyi/OpenBLAS/issues/834 or other.
