### ISSUE TITLE
Change docker image

### ISSUE THREAD

**Issue by xianyi** [xianyi/OpenBLAS-CI#3]
See numpy/numpy#7500 , change the  docker image.

When I ran `apt-get update` in docker, I met

```
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

After google, I found this may be related to the network provide.

Then, I think we need to use (or build) a docker image, which is already installed gcc, gfortran, make, python.

@matthew-brett

**Comment by matthew-brett** [comment]
Sorry - I don't understand.  You are already in the manylinux docker image when you run `apt-get`?

How do you start the docker image to make the buildslave instance?

**Comment by xianyi** [comment]
When I tried to use travis-ci docker image (current tag packer-1457060342), I met this error.

I din't run `apt-get` on manylinux docker image. Therefore, I didn't meet this error. If I use `apt-get` on manylinux image, I will meet the similar error.

Then, I want to use or build an image with update-to-date libc, python, gcc toolchain, and others, to avoid `apt-get`.

**Comment by matthew-brett** [comment]
The two options would be to pull the dependencies into a standard ubuntu image, or use a new one.

To make an image with everything you need, I think you can just do:

```
docker run -ti --rm ubuntu:14.04 /bin/bash
apt-get update
apt-get install -y build-essential python-dev python-pip gfortran git
```

I built a new image from ubuntu:14.04 with this Dockerfile : https://gist.github.com/16a2996f52971cc18dfccb8277c3ff41

The image is here : https://hub.docker.com/r/matthewbrett/openblas/ if you'd prefer to use that:

```
docker pull matthewbrett/openblas:14.04
```

**Comment by ogrisel** [comment]
To test python related stuff I would advise your to install the official python image. It already has gcc and other dev tools. You just need to add gfortran for numpy / scipy tests:

```
docker run -ti --rm python:3.5 /bin/bash
apt-get update -yqq && apt-get install -y gfortran
```

It is based on a quite recent debian and maintained by the docker core team.

**Comment by ogrisel** [comment]
This should be fixed by #5 and #7. Let's wait a bit to see if the numpy tests pass now.

**Comment by ogrisel** [comment]
Ok the docker image work. The is a test failure in a scipy test on AMD CPUs but I think this should be tracked by another issue.

**Comment by xianyi** [comment]
@ogrisel , 

when I want to setup a new build slave, I met the following error.

```
docker build -t xianyi/openblas-ci .
Sending build context to Docker daemon 83.97 kB
Sending build context to Docker daemon 
Step 0 : FROM python:2.7
 ---> 6087f74a2b3c
Step 1 : MAINTAINER Zhang Xianyi <traits.zhang@gmail.com>
 ---> Using cache
 ---> eba2d6e6bdc1
Step 2 : RUN apt-get update -yqq   && apt-get install -yqq gfortran   && rm -rf /var/lib/apt/lists/*
 ---> Running in fbbdb6137e64
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/g/gcc-4.9/gfortran-4.9_4.9.2-10_amd64.deb  405  Not Allowed

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
INFO[0037] The command [/bin/sh -c apt-get update -yqq   && apt-get install -yqq gfortran   && rm -rf /var/lib/apt/lists/*] returned a non-zero code: 100 
```

Is it possible to find a (free or low cost) docker image host?

**Comment by xianyi** [comment]
Upload the image to https://cloud.docker.com/repository/show/xianyi/openblas-ci/

**Comment by ogrisel** [comment]
The traditional host is hub.docker.com and is I think it is still free for public images and you can register github repo with Dockerfile to get the image be updated automatically. There is also https://quay.io.

I did not know about  https://cloud.docker.com/repository.
